#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef BIOMETRICFACEVALIDATOR_SWIFT_H
#define BIOMETRICFACEVALIDATOR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BiometricFaceValidator",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

/// Ajustes de política do controle de acesso.
/// Tudo aqui é decisão de operação, não de biometria — por isso vem em uma classe própria e
/// com valores que fazem sentido numa catraca de prédio.
SWIFT_CLASS_NAMED("BTAccessConfig")
@interface BTAccessConfig : NSObject
@property (nonatomic, copy) NSString * _Nonnull apiUrl;
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic) BOOL useFrontCamera;
/// Revogar a liberação quando aparecer um rosto sem match antes de a pessoa passar.
/// É o que impede a carona: alguém autorizado libera a catraca e outra pessoa entra junto.
/// Ligado por padrão; desligue quando a catraca já tratar isso por hardware.
@property (nonatomic) BOOL revokeOnMismatch;
/// Quanto tempo a liberação vale sem ninguém passar. Depois disso, rearma sozinha.
/// Existe como rede de proteção: se o sensor da catraca falhar e ninguém chamar
/// <code>personPassed()</code>, o terminal voltaria a funcionar em vez de ficar morto.
@property (nonatomic) NSInteger releaseWindowSeconds;
/// Trava depois de um rosto que passou na vivacidade mas não está na base.
/// Menor que a janela de liberação porque não há catraca girando para esperar — só evita
/// consultar o servidor em rajada com a pessoa parada na frente.
@property (nonatomic) NSInteger unknownCooldownSeconds;
/// Sem rosto por este tempo, avisa que está ocioso. Zero desliga o aviso.
@property (nonatomic) NSInteger idleSeconds;
/// Manter a câmera aberta procurando presença quando não há sensor de movimento.
@property (nonatomic) BOOL watchForFace;
/// Nome do ponto de acesso, para identificar o terminal na administração.
@property (nonatomic, copy) NSString * _Nullable terminalLabel;
/// Deixar a configuração do ponto, feita no Dashboard, sobrepor o que está aqui.
/// Ligado por padrão. Desligue só quando o aplicativo tiver motivo próprio para mandar —
/// um totem que também é catraca, por exemplo — porque desligado o terminal deixa de
/// responder à administração e passa a depender de novo deploy para qualquer ajuste.
@property (nonatomic) BOOL useServerPolicy;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class BTAccessSession;
enum BTAccessState : NSInteger;

/// O que a sessão comunica ao aplicativo de controle de acesso.
/// Deliberadamente não existe nada aqui sobre catraca, relé ou porta: acionar o equipamento é
/// do integrador, que conhece o protocolo dele. A sessão diz o que enxergou e o que decidiu.
SWIFT_PROTOCOL_NAMED("BTAccessDelegate")
@protocol BTAccessDelegate
- (void)accessSession:(BTAccessSession * _Nonnull)session didChangeState:(enum BTAccessState)state;
@optional
/// Alguém entrou ou saiu do campo da câmera. Serve para acender a tela e apagar depois.
- (void)accessSession:(BTAccessSession * _Nonnull)session didDetectPresence:(BOOL)present;
@required
/// Rosto reconhecido: pode liberar.
- (void)accessSession:(BTAccessSession * _Nonnull)session didAuthorize:(NSString * _Nonnull)personId name:(NSString * _Nonnull)name document:(NSString * _Nonnull)document confidence:(double)confidence;
@optional
/// Liberação revogada antes de a pessoa passar. Feche de novo.
- (void)accessSessionDidRevoke:(BTAccessSession * _Nonnull)session;
/// Rosto vivo, mas não está na base.
- (void)accessSessionDidFindUnknown:(BTAccessSession * _Nonnull)session;
/// Não passou na vivacidade, ou a leitura falhou.
- (void)accessSession:(BTAccessSession * _Nonnull)session didDeny:(NSString * _Nonnull)message;
/// Tempo sem ninguém na frente. Momento de mostrar a tela de espera.
- (void)accessSessionDidBecomeIdle:(BTAccessSession * _Nonnull)session;
/// Onde o rosto está no vídeo, em coordenadas normalizadas (0..1, origem no topo-esquerda).
/// Chega a cada frame com alguém no campo. Serve para desenhar o quadro sobre a câmera —
/// e continua chegando com a análise suspensa, porque a pessoa continua ali.
- (void)accessSession:(BTAccessSession * _Nonnull)session didTrackFace:(CGRect)box;
/// O que o motor está fazendo agora, em uma ou duas linhas.
/// Para o aplicativo mostrar na tela durante uma instalação ou uma investigação. Num
/// terminal na parede não há console do Xcode: sem isto, “aparece o rosto e nada
/// acontece” não tem como ser diagnosticado no lugar onde acontece.
- (void)accessSession:(BTAccessSession * _Nonnull)session didReportDiagnostics:(NSString * _Nonnull)texto;
/// Reconhecida, e sem permissão para ESTE ponto.
/// Separado de <code>didFindUnknown</code> porque a portaria trata os dois casos de forma diferente:
/// um rosto desconhecido é visita, e um morador na porta errada é orientação. Mostrar
/// “não reconhecido” para quem está cadastrado manda a pessoa procurar o cadastro que ela
/// já tem.
- (void)accessSessionDidDenyPermission:(BTAccessSession * _Nonnull)session reason:(NSString * _Nonnull)reason;
@end

@class UIView;

/// FaceMatch contínuo para controle de acesso.
/// Diferente de <code>BTValidationLauncher</code>, que abre uma tela, faz uma leitura e sai, esta sessão
/// fica de pé sobre uma view do integrador e entrega uma decisão por pessoa.
/// A regra que a torna utilizável numa catraca: <em>uma liberação por armação</em>. Depois de
/// autorizar, a sessão para de autorizar — não importa quantos rostos passem na frente — até
/// que o integrador avise que a pessoa passou, ou até a janela vencer. Sem isso, uma pessoa
/// parada em frente ao aparelho geraria liberação atrás de liberação.
SWIFT_CLASS_NAMED("BTAccessSession")
@interface BTAccessSession : NSObject
@property (nonatomic, readonly) enum BTAccessState state;
@property (nonatomic, weak) id <BTAccessDelegate> _Nullable delegate;
/// Nome do ponto onde este terminal está instalado, quando o servidor informou.
@property (nonatomic, readonly, copy) NSString * _Nullable accessPointName;
- (nonnull instancetype)initWithConfig:(BTAccessConfig * _Nonnull)config OBJC_DESIGNATED_INITIALIZER;
/// Abre a câmera sobre a view informada.
/// Chame quando o sensor de movimento acusar alguém, ou uma vez só, se o aparelho não
/// tiver sensor e você preferir deixar a vigília por rosto cuidando disso.
- (void)startIn:(UIView * _Nonnull)previewView;
/// Fecha a câmera e volta ao repouso.
- (void)stop;
/// A pessoa passou pela catraca: pode voltar a procurar.
/// É o sinal que o integrador dá a partir do sensor do equipamento. Sem ele, a sessão só
/// rearma quando a janela de liberação vence.
- (void)personPassed;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Em que ponto do ciclo a sessão está.
typedef SWIFT_ENUM(NSInteger, BTAccessState, open) {
/// Câmera desligada.
  BTAccessStateParada = 0,
/// Câmera aberta, só olhando se aparece alguém. Não consulta o servidor.
  BTAccessStateVigilia = 1,
/// Alguém apareceu: rodando vivacidade e busca.
  BTAccessStateProcurando = 2,
/// Acesso liberado. Continua olhando, mas só para revogar.
  BTAccessStateLiberada = 3,
/// Liberação revogada: apareceu rosto sem match antes de a pessoa passar.
  BTAccessStateBloqueada = 4,
};

/// Posição da marca do cliente na tela de captura.
typedef SWIFT_ENUM(NSInteger, BTBrandPosition, open) {
  BTBrandPositionBottomLeft = 0,
  BTBrandPositionBottomRight = 1,
  BTBrandPositionTopLeft = 2,
  BTBrandPositionTopRight = 3,
};

/// Tipo de documento, no formato que atravessa a fronteira para Objective-C.
/// O enum Swift usa String como valor bruto, o que não é exportável. A conversão fica aqui e
/// não em cada binding.
typedef SWIFT_ENUM(NSInteger, BTDocumentType, open) {
  BTDocumentTypeCpf = 0,
  BTDocumentTypeRg = 1,
  BTDocumentTypeCnh = 2,
};

@class UIViewController;
@class BTFaceMatchManagerResult;
@class UIImage;

/// Cadastro do FaceMatch com tela própria, visível a Objective-C.
/// Mesmo desenho de <code>BTValidationLauncher</code>: bloco no lugar de protocolo, entregue uma única vez
/// na main thread. É o que o pacote MAUI e o React Native consomem.
SWIFT_CLASS_NAMED("BTFaceMatchManagerLauncher")
@interface BTFaceMatchManagerLauncher : NSObject
- (nonnull instancetype)initWithApiUrl:(NSString * _Nonnull)apiUrl uuid:(NSString * _Nonnull)uuid locale:(NSString * _Nullable)locale themeMode:(NSString * _Nullable)themeMode requireChallenges:(BOOL)requireChallenges OBJC_DESIGNATED_INITIALIZER;
/// Cadastra uma pessoa nova: abre a captura e grava o rosto aprovado.
- (void)addPersonFrom:(UIViewController * _Nonnull)viewController name:(NSString * _Nonnull)name document:(NSString * _Nonnull)document documentType:(enum BTDocumentType)documentType completion:(void (^ _Nonnull)(BTFaceMatchManagerResult * _Nonnull))completion;
/// Cadastra a partir de uma imagem escolhida, sem abrir a câmera.
/// A imagem passa pelo modelo local de vivacidade antes de sair do aparelho, e o servidor
/// roda o próprio modelo de novo no cadastro.
- (void)addPersonWithImage:(UIImage * _Nonnull)image name:(NSString * _Nonnull)name document:(NSString * _Nonnull)document documentType:(enum BTDocumentType)documentType completion:(void (^ _Nonnull)(BTFaceMatchManagerResult * _Nonnull))completion;
/// Troca a foto de uma pessoa já cadastrada.
- (void)editPersonFrom:(UIViewController * _Nonnull)viewController uniqueId:(NSString * _Nonnull)uniqueId name:(NSString * _Nonnull)name document:(NSString * _Nonnull)document completion:(void (^ _Nonnull)(BTFaceMatchManagerResult * _Nonnull))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Resultado de um cadastro ou atualização no FaceMatch.
SWIFT_CLASS_NAMED("BTFaceMatchManagerResult")
@interface BTFaceMatchManagerResult : NSObject
@property (nonatomic, readonly) BOOL isSuccess;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
/// Identificador da pessoa criada. Vazio numa atualização, que não cria nada.
@property (nonatomic, readonly, copy) NSString * _Nullable uniqueId;
/// A tela foi fechada sem concluir — nem sucesso, nem erro.
@property (nonatomic, readonly) BOOL cancelled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum BTValidationMode : NSInteger;
@class NSDate;

/// Configuração de uma validação.
/// Propriedades simples em vez de builder encadeado: builder com retorno de <code>Self</code> fica
/// desconfortável em Objective-C e não traz ganho para quem consome via binding.
SWIFT_CLASS_NAMED("BTValidationConfig")
@interface BTValidationConfig : NSObject
@property (nonatomic, copy) NSString * _Nullable uuid;
@property (nonatomic, copy) NSString * _Nullable apiUrl;
@property (nonatomic) enum BTValidationMode validationMode;
@property (nonatomic) NSInteger challengeCount;
@property (nonatomic) BOOL requireAllChallenges;
/// Vale para <code>faceMatch</code> e <code>faceMatchExact</code>. No Swift viaja dentro do case.
@property (nonatomic) BOOL requireChallenges;
/// Obrigatório em <code>faceMatchExact</code>: o documento que a pessoa diz ser.
@property (nonatomic, copy) NSString * _Nullable documentNumber;
/// Obrigatórios em <code>livenessWithDocument</code>.
@property (nonatomic, copy) NSString * _Nullable documentCpf;
@property (nonatomic, copy) NSDate * _Nullable documentBirthDate;
@property (nonatomic) NSInteger timeoutMillis;
@property (nonatomic, copy) NSString * _Nullable locale;
@property (nonatomic, copy) NSString * _Nullable themeMode;
@property (nonatomic) BOOL enableSoundFeedback;
@property (nonatomic) BOOL enableHapticFeedback;
@property (nonatomic, strong) UIImage * _Nullable cornerImage;
@property (nonatomic) enum BTBrandPosition cornerImagePosition;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class BTValidationResult;

/// Abre a validação e devolve o resultado por bloco.
/// Um bloco no lugar do protocolo de callback: binding não precisa implementar protocolo
/// nem manter objeto vivo, e o mesmo formato serve para .NET, React Native e Flutter.
SWIFT_CLASS_NAMED("BTValidationLauncher")
@interface BTValidationLauncher : NSObject
- (nonnull instancetype)initWithConfig:(BTValidationConfig * _Nonnull)config OBJC_DESIGNATED_INITIALIZER;
/// Abre a tela de validação. O bloco é chamado UMA vez, sempre na thread principal.
- (void)launchFrom:(UIViewController * _Nonnull)viewController completion:(void (^ _Nonnull)(BTValidationResult * _Nonnull))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Modo de validação, achatado para Objective-C.
/// Os parâmetros que no Swift viajam dentro do case (<code>requireChallenges</code>, <code>documentNumber</code>)
/// ficam em <code>BTValidationConfig</code>, como no Android.
typedef SWIFT_ENUM(NSInteger, BTValidationMode, open) {
  BTValidationModeLivenessOnly = 0,
  BTValidationModeLivenessWithDocument = 1,
  BTValidationModeFaceMatch = 2,
  BTValidationModeFaceMatchExact = 3,
  BTValidationModeFaceCapture = 4,
};

@class NSNumber;

/// Resultado de uma validação, achatado.
/// Tudo é propriedade, e não método <code>get…()</code>: propriedade vira <code>@property</code> no cabeçalho,
/// o que qualquer binding lê como campo em vez de chamada.
SWIFT_CLASS_NAMED("BTValidationResult")
@interface BTValidationResult : NSObject
@property (nonatomic, readonly) BOOL isSuccess;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly) float vivacityConfidence;
@property (nonatomic, readonly, strong) UIImage * _Nullable faceImage;
@property (nonatomic, readonly) enum BTValidationMode validationMode;
@property (nonatomic, readonly) BOOL hasDocumentValidation;
@property (nonatomic, readonly) float documentSimilarity;
@property (nonatomic, readonly, copy) NSString * _Nullable documentFullName;
@property (nonatomic, readonly, copy) NSString * _Nullable documentNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable documentBirthDate;
@property (nonatomic, readonly, copy) NSString * _Nullable documentProbability;
@property (nonatomic, readonly) BOOL hasFaceMatchValidation;
/// <code>NSNumber</code> em vez de <code>Bool</code> porque o valor pode ser AUSENTE — e ausente é diferente
/// de “não deu match”. Um <code>Bool</code> puro apagaria essa distinção.
@property (nonatomic, readonly, strong) NSNumber * _Nullable match;
@property (nonatomic, readonly, copy) NSString * _Nullable matchedPersonId;
@property (nonatomic, readonly, strong) NSNumber * _Nullable matchConfidence;
@property (nonatomic, readonly, copy) NSString * _Nullable personName;
@property (nonatomic, readonly, copy) NSString * _Nullable personDocument;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Dados para autenticação biométrica
SWIFT_CLASS("_TtC22BiometricFaceValidator16BioTrustAuthData")
@interface BioTrustAuthData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull packageName;
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, readonly, copy) NSString * _Nonnull validationType;
@property (nonatomic, readonly, copy) NSString * _Nonnull document;
@property (nonatomic, readonly, copy) NSString * _Nonnull dob;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceID;
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull so;
@property (nonatomic, readonly, copy) NSString * _Nonnull soVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull ipAddress;
@property (nonatomic, readonly, copy) NSString * _Nonnull requestId;
- (nonnull instancetype)initWithPackageName:(NSString * _Nonnull)packageName uuid:(NSString * _Nonnull)uuid validationType:(NSString * _Nonnull)validationType document:(NSString * _Nonnull)document dob:(NSString * _Nonnull)dob ipAddress:(NSString * _Nonnull)ipAddress requestId:(NSString * _Nonnull)requestId deviceId:(NSString * _Nonnull)deviceId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPackageName:(NSString * _Nonnull)packageName uuid:(NSString * _Nonnull)uuid validationType:(NSString * _Nonnull)validationType document:(NSString * _Nonnull)document dob:(NSString * _Nonnull)dob deviceID:(NSString * _Nonnull)deviceID sdkVersion:(NSString * _Nonnull)sdkVersion so:(NSString * _Nonnull)so soVersion:(NSString * _Nonnull)soVersion ipAddress:(NSString * _Nonnull)ipAddress requestId:(NSString * _Nonnull)requestId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Gerenciador principal do BioTrust
/// Interface Swift para facilitar o uso do framework
SWIFT_CLASS("_TtC22BiometricFaceValidator15BioTrustManager")
@interface BioTrustManager : NSObject
/// Instância singleton
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BioTrustManager * _Nonnull shared;)
+ (BioTrustManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Inicializa o BioTrust
/// Deve ser chamado antes de usar qualquer funcionalidade
- (void)initialize;
/// Limpa recursos do BioTrust
- (void)cleanup;
/// Criptografa um texto
/// @param plaintext Texto a ser criptografado
/// @return Texto criptografado ou nil se houver erro
- (NSString * _Nullable)encrypt:(NSString * _Nonnull)plaintext SWIFT_WARN_UNUSED_RESULT;
/// Descriptografa um texto
/// @param ciphertext Texto criptografado
/// @return Texto descriptografado ou nil se houver erro
- (NSString * _Nullable)decrypt:(NSString * _Nonnull)ciphertext SWIFT_WARN_UNUSED_RESULT;
/// Gera payload de autenticação com informações automáticas do dispositivo
- (NSString * _Nullable)generateAuthPayloadWithPackageName:(NSString * _Nonnull)packageName uuid:(NSString * _Nonnull)uuid validationType:(NSString * _Nonnull)validationType document:(NSString * _Nonnull)document dob:(NSString * _Nonnull)dob ipAddress:(NSString * _Nonnull)ipAddress requestId:(NSString * _Nonnull)requestId deviceId:(NSString * _Nonnull)deviceId SWIFT_WARN_UNUSED_RESULT;
/// Gera payload de autenticação com parâmetros customizados
- (NSString * _Nullable)generateAuthPayloadWithPackageName:(NSString * _Nonnull)packageName uuid:(NSString * _Nonnull)uuid validationType:(NSString * _Nonnull)validationType document:(NSString * _Nonnull)document dob:(NSString * _Nonnull)dob deviceID:(NSString * _Nonnull)deviceID sdkVersion:(NSString * _Nonnull)sdkVersion so:(NSString * _Nonnull)so soVersion:(NSString * _Nonnull)soVersion ipAddress:(NSString * _Nonnull)ipAddress requestId:(NSString * _Nonnull)requestId SWIFT_WARN_UNUSED_RESULT;
@end

@class DeviceInfo;

@interface BioTrustManager (SWIFT_EXTENSION(BiometricFaceValidator))
/// Gera payload usando estrutura de dados
- (NSString * _Nullable)generateAuthPayloadWith:(BioTrustAuthData * _Nonnull)authData SWIFT_WARN_UNUSED_RESULT;
/// Obtém informações do dispositivo
- (DeviceInfo * _Nonnull)getDeviceInfo SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC22BiometricFaceValidator10DeviceInfo")
@interface DeviceInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceID;
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull operatingSystem;
@property (nonatomic, readonly, copy) NSString * _Nonnull systemVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceModel;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceName;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (NSDictionary<NSString *, NSString *> * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SDKVersionInfo;

/// Helper para obter informações do dispositivo e sistema
SWIFT_CLASS("_TtC22BiometricFaceValidator16DeviceInfoHelper")
@interface DeviceInfoHelper : NSObject
/// Nome do sistema operacional
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull operatingSystem;)
+ (NSString * _Nonnull)operatingSystem SWIFT_WARN_UNUSED_RESULT;
/// Obtém a versão real do SDK BiometricFaceValidator do Bundle
/// Funciona perfeitamente com $(MARKETING_VERSION) e $(CURRENT_PROJECT_VERSION)
+ (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
/// Obtém informações detalhadas da versão do SDK
/// Funciona com variáveis do Xcode (MARKETING_VERSION, CURRENT_PROJECT_VERSION)
+ (SDKVersionInfo * _Nonnull)getSDKVersionInfo SWIFT_WARN_UNUSED_RESULT;
/// Obtém o identificador único e permanente do dispositivo
+ (NSString * _Nonnull)getDeviceID SWIFT_WARN_UNUSED_RESULT;
/// Força a regeneração do Device ID (apenas para debug/testes)
+ (NSString * _Nonnull)regenerateDeviceID SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getSystemVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getDeviceModel SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getDeviceName SWIFT_WARN_UNUSED_RESULT;
+ (DeviceInfo * _Nonnull)getDeviceInfo SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceInfoHelper (SWIFT_EXTENSION(BiometricFaceValidator))
+ (void)printDeviceInfo;
+ (BOOL)isDeviceIDSaved SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getCurrentIdentifierForVendor SWIFT_WARN_UNUSED_RESULT;
@end


/// Abre a tela de cadastro do FaceMatch.
/// Antes disto, cadastrar uma pessoa no iOS era um trabalho do aplicativo: abrir uma captura,
/// tirar a foto do jeito que desse, e chamar <code>FaceMatchService</code> por conta própria. Duas coisas
/// saíam erradas nesse caminho — a foto não passava por prova de vida, então dava para cadastrar
/// uma pessoa a partir de uma foto impressa; e cada aplicativo resolvia a captura de um jeito,
/// então a qualidade do rosto que entrava na base variava de integrador para integrador. No
/// Android e na Web isso nunca aconteceu, porque lá o cadastro sempre teve tela própria.
/// Aqui a tela é a mesma da validação, no modo de captura: o mesmo oval, os mesmos desafios,
/// a mesma prova de vida. Só o final muda — em vez de consultar, grava.
SWIFT_CLASS("_TtC22BiometricFaceValidator24FaceMatchManagerLauncher")
@interface FaceMatchManagerLauncher : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC22BiometricFaceValidator14SDKVersionInfo")
@interface SDKVersionInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
@property (nonatomic, readonly, copy) NSString * _Nonnull buildNumber;
@property (nonatomic, readonly, copy) NSString * _Nonnull bundleIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull bundleName;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (NSString * _Nonnull)fullVersion SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
